# Generated by Django 5.1.1 on 2024-10-10 08:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("webooks", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="book",
            name="author",
        ),
        migrations.RemoveField(
            model_name="book",
            name="genre",
        ),
        migrations.RemoveField(
            model_name="shelfbook",
            name="book",
        ),
        migrations.RemoveField(
            model_name="review",
            name="book",
        ),
        migrations.RemoveField(
            model_name="review",
            name="user",
        ),
        migrations.RemoveField(
            model_name="shelf",
            name="user",
        ),
        migrations.RemoveField(
            model_name="shelfbook",
            name="shelf",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="user",
        ),
        migrations.DeleteModel(
            name="Author",
        ),
        migrations.DeleteModel(
            name="Genre",
        ),
        migrations.DeleteModel(
            name="Book",
        ),
        migrations.DeleteModel(
            name="Review",
        ),
        migrations.DeleteModel(
            name="Shelf",
        ),
        migrations.DeleteModel(
            name="ShelfBook",
        ),
        migrations.DeleteModel(
            name="UserProfile",
        ),
    ]
