# Generated by Django 5.1.1 on 2024-10-12 13:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("webooks", "0003_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="cover",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="pfp",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
    ]
