# Generated by Django 5.1.1 on 2024-10-15 13:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("webooks", "0004_alter_book_cover_alter_userprofile_pfp"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                ],
                default="pending",
                max_length=10,
            ),
        ),
    ]
