# Generated by Django 5.1.1 on 2024-10-15 16:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("webooks", "0005_alter_book_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="pfp",
            field=models.ImageField(
                blank=True,
                default="https://static.vecteezy.com/system/resources/previews/009/292/244/non_2x/default-avatar-icon-of-social-media-user-vector.jpg",
                null=True,
                upload_to="",
            ),
        ),
    ]
