# Generated by Django 5.1.1 on 2024-10-16 07:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("webooks", "0006_alter_userprofile_pfp"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="cover",
            field=models.ImageField(
                blank=True,
                default="https://api.chaladsue.com/api/public/articles/photo/undefined",
                null=True,
                upload_to="",
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="pfp",
            field=models.ImageField(
                blank=True, default="https://shorturl.at/QYuov", null=True, upload_to=""
            ),
        ),
    ]
