# Generated by Django 5.1.1 on 2024-10-16 09:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("webooks", "0007_alter_book_cover_alter_userprofile_pfp"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="cover",
            field=models.ImageField(
                blank=True, default="https://shorturl.at/HIdup", null=True, upload_to=""
            ),
        ),
    ]
