# Generated by Django 5.1.1 on 2024-10-16 09:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("webooks", "0009_alter_book_cover"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="pfp",
            field=models.TextField(
                blank=True, default="https://shorturl.at/QYuov", null=True
            ),
        ),
    ]
