# Generated by Django 5.1.1 on 2024-10-16 12:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("webooks", "0010_alter_userprofile_pfp"),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="status",
            field=models.CharField(
                choices=[("ok", "OK"), ("hidden", "Hidden")],
                default="ok",
                max_length=10,
            ),
        ),
    ]
