# Generated by Django 5.1.1 on 2024-10-16 14:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("webooks", "0011_review_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shelf",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="shelves",
                to="webooks.userprofile",
            ),
        ),
    ]
