# Generated by Django 5.1.1 on 2024-10-16 15:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("webooks", "0012_alter_shelf_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                    ("removed", "Removed"),
                ],
                default="pending",
                max_length=10,
            ),
        ),
    ]
